export const restaurants = [
  {
    "id": 1,
    "name": "Warung Nusantara",
    "icon": "🏮",
    "cuisine": "Masakan Indonesia Tradisional",
    "description": "Cita rasa autentik Nusantara dari berbagai daerah Indonesia",
    "kitchenStatus": "normal",
    "avgTime": "±0m",
    "image": "/images/no-preview.svg",
    "menuCount": 8,
    "maxCapacity": 3
  },
  {
    "id": 2,
    "name": "Sakura Ramen House",
    "icon": "🍜",
    "cuisine": "Masakan Jepang Modern",
    "description": "Ramen dan hidangan Jepang autentik dengan sentuhan modern",
    "kitchenStatus": "busy",
    "avgTime": "+5-10m",
    "image": "/images/no-preview.svg",
    "menuCount": 8,
    "maxCapacity": 3
  },
  {
    "id": 3,
    "name": "Green Bowl Café",
    "icon": "🥗",
    "cuisine": "Healthy & Plant-Based",
    "description": "Hidangan sehat dan plant-based untuk gaya hidup modern",
    "kitchenStatus": "very-busy",
    "avgTime": "+15-20m",
    "image": "/images/no-preview.svg",
    "menuCount": 8,
    "maxCapacity": 3
  }
];

export const menus = [
  {
    "id": 1,
    "restaurantId": 1,
    "name": "Nasi Goreng Kampung",
    "description": "Nasi goreng khas kampung dengan bumbu rempah pilihan, telur mata sapi, dan kerupuk.",
    "price": 28000,
    "image": "/images/Nasigoreng.JPG",
    "category": "makanan-utama",
    "weight": "350g",
    "servingSize": "1 orang",
    "pieces": null,
    "calories": 450,
    "ingredients": ["Nasi Putih", "Telur Ayam", "Kecap Manis", "Bawang Merah", "Bawang Putih", "Cabai Rawit", "Minyak Goreng"],
    "allergens": [],
    "healthCategory": "orange",
    "prepTime": 8,
    "prepSpeed": "fast",
    "isPopular": true,
    "isNew": false
  },
  {
    "id": 2,
    "restaurantId": 1,
    "name": "Soto Ayam Lamongan",
    "description": "Soto ayam gurih dengan koya spesial, bihun, telur rebus, dan suwiran ayam kampung.",
    "price": 25000,
    "image": "/images/Soto.JPG",
    "category": "makanan-utama",
    "weight": "300g",
    "servingSize": "1 orang",
    "pieces": null,
    "calories": 280,
    "ingredients": ["Ayam Kampung", "Bihun", "Kol", "Telur Rebus", "Bubuk Koya", "Jeruk Nipis", "Bawang Goreng"],
    "allergens": [],
    "healthCategory": "green",
    "prepTime": 15,
    "prepSpeed": "slow",
    "isPopular": false,
    "isNew": false
  },
  {
    "id": 3,
    "restaurantId": 1,
    "name": "Rendang Sapi",
    "description": "Potongan daging sapi empuk dimasak perlahan dengan santan dan rempah khas Padang.",
    "price": 45000,
    "image": "/images/rendang.jpg",
    "category": "makanan-utama",
    "weight": "250g",
    "servingSize": "1 orang",
    "pieces": null,
    "calories": 520,
    "ingredients": ["Daging Sapi", "Santan", "Cabai Merah", "Bawang Merah", "Bawang Putih", "Jahe", "Lengkuas"],
    "allergens": [],
    "healthCategory": "orange",
    "prepTime": 20,
    "prepSpeed": "slow",
    "isPopular": true,
    "isNew": false
  },
  {
    "id": 4,
    "restaurantId": 1,
    "name": "Gado-gado Jakarta",
    "description": "Sayuran segar dengan saus kacang gurih manis dan kerupuk renyah.",
    "price": 22000,
    "image": "/images/Gadogado.JPG",
    "category": "makanan-utama",
    "weight": "280g",
    "servingSize": "1 orang",
    "pieces": null,
    "calories": 320,
    "ingredients": ["Kacang Tanah", "Tahu", "Tempe", "Lontong", "Tauge", "Kangkung", "Telur Rebus"],
    "allergens": ["Kacang Tanah"],
    "healthCategory": "orange",
    "prepTime": 5,
    "prepSpeed": "fast",
    "isPopular": false,
    "isNew": false
  },
  {
    "id": 5,
    "restaurantId": 1,
    "name": "Ayam Bakar Taliwang",
    "description": "Ayam bakar bumbu Taliwang khas Lombok dengan cita rasa pedas gurih yang meresap.",
    "price": 38000,
    "image": "/images/Ayam.JPG",
    "category": "makanan-utama",
    "weight": "300g",
    "servingSize": "1 orang",
    "pieces": null,
    "calories": 480,
    "ingredients": ["Ayam Broiler", "Cabai Merah", "Bawang Merah", "Terasi", "Kencur", "Minyak Kelapa"],
    "allergens": [],
    "healthCategory": "orange",
    "prepTime": 18,
    "prepSpeed": "slow",
    "isPopular": false,
    "isNew": false
  },
  {
    "id": 6,
    "restaurantId": 1,
    "name": "Pecel Lele Lalapan",
    "description": "Lele goreng garing dengan lalapan segar dan sambal terasi pedas mantap.",
    "price": 30000,
    "image": "/images/Lele.JPG",
    "category": "makanan-utama",
    "weight": "320g",
    "servingSize": "1 orang",
    "pieces": null,
    "calories": 390,
    "ingredients": ["Ikan Lele", "Nasi Putih", "Lalapan", "Cabai Rawit", "Bawang Merah", "Tomat"],
    "allergens": [],
    "healthCategory": "green",
    "prepTime": 10,
    "prepSpeed": "fast",
    "isPopular": false,
    "isNew": false
  },
  {
    "id": 7,
    "restaurantId": 1,
    "name": "Nasi Uduk Betawi",
    "description": "Nasi uduk gurih harum daun salam & serai disajikan dengan lauk pauk lengkap.",
    "price": 20000,
    "image": "/images/Nasiuduk.JPG",
    "category": "makanan-utama",
    "weight": "300g",
    "servingSize": "1 orang",
    "pieces": null,
    "calories": 380,
    "ingredients": ["Nasi Uduk", "Bihun Goreng", "Tempe Orek", "Telur Iris", "Kerupuk"],
    "allergens": [],
    "healthCategory": "green",
    "prepTime": 5,
    "prepSpeed": "fast",
    "isPopular": false,
    "isNew": false
  },
  {
    "id": 8,
    "restaurantId": 1,
    "name": "Es Cendol",
    "description": "Minuman cendol santan manis gurih dengan gula aren murni khas Nusantara.",
    "price": 12000,
    "image": "/images/Cendol.JPG",
    "category": "minuman",
    "weight": "250ml",
    "servingSize": "1 orang",
    "pieces": null,
    "calories": 180,
    "ingredients": ["Cendol Pandan", "Santan", "Gula Aren", "Susu Sapi", "Es Batu"],
    "allergens": ["Susu"],
    "healthCategory": "blue",
    "prepTime": 3,
    "prepSpeed": "fast",
    "isPopular": false,
    "isNew": false
  },
  {
    "id": 9,
    "restaurantId": 2,
    "name": "Tonkotsu Ramen",
    "description": "Ramen Jepang khas dengan kaldu kental gurih, chashu empuk, dan telur nitamago.",
    "price": 42000,
    "image": "/images/Tonkotsuramen.jpg",
    "category": "makanan-utama",
    "weight": "450g",
    "servingSize": "1 orang",
    "pieces": null,
    "calories": 550,
    "ingredients": ["Mie Ramen", "Kaldu Gurih", "Telur Nitamago", "Chashu", "Daun Bawang", "Nori"],
    "allergens": ["Gluten"],
    "healthCategory": "orange",
    "prepTime": 15,
    "prepSpeed": "slow",
    "isPopular": true,
    "isNew": false
  },
  {
    "id": 10,
    "restaurantId": 2,
    "name": "Chicken Katsu Curry",
    "description": "Chicken katsu renyah disiram saus kari Jepang yang kaya rasa.",
    "price": 38000,
    "image": "/images/Chickenkatsu.jpg",
    "category": "makanan-utama",
    "weight": "380g",
    "servingSize": "1 orang",
    "pieces": null,
    "calories": 620,
    "ingredients": ["Daging Ayam", "Tepung Panko", "Kari Jepang", "Wortel", "Kentang", "Nasi"],
    "allergens": ["Gluten"],
    "healthCategory": "orange",
    "prepTime": 12,
    "prepSpeed": "slow",
    "isPopular": false,
    "isNew": false
  },
  {
    "id": 11,
    "restaurantId": 2,
    "name": "Salmon Sashimi",
    "description": "Irisan daging salmon segar pilihan dengan tekstur lembut melted di mulut.",
    "price": 55000,
    "image": "/images/Salmon.jpg",
    "category": "makanan-utama",
    "weight": "150g",
    "servingSize": "1 orang",
    "pieces": null,
    "calories": 180,
    "ingredients": ["Daging Salmon Segar", "Wasabi", "Shoyu"],
    "allergens": ["Seafood"],
    "healthCategory": "green",
    "prepTime": 5,
    "prepSpeed": "fast",
    "isPopular": true,
    "isNew": false
  },
  {
    "id": 12,
    "restaurantId": 2,
    "name": "Ebi Tempura",
    "description": "Udang goreng tempura renyah disajikan dengan dipping sauce khas Jepang.",
    "price": 35000,
    "image": "/images/Ebitempura.jpg",
    "category": "makanan-utama",
    "weight": "200g",
    "servingSize": "1 orang",
    "pieces": "6 pcs",
    "calories": 340,
    "ingredients": ["Udang Segar", "Tepung Tempura", "Minyak Wijen"],
    "allergens": ["Seafood", "Gluten"],
    "healthCategory": "pink",
    "prepTime": 8,
    "prepSpeed": "fast",
    "isPopular": false,
    "isNew": false
  },
  {
    "id": 13,
    "restaurantId": 2,
    "name": "Edamame",
    "description": "Kacang edamame kukus gurih disajikan hangat dengan sedikit taburan garam.",
    "price": 18000,
    "image": "/images/Edamame.jpg",
    "category": "snack",
    "weight": "150g",
    "servingSize": "1 orang",
    "pieces": null,
    "calories": 120,
    "ingredients": ["Kacang Edamame", "Garam Laut"],
    "allergens": ["Kedelai"],
    "healthCategory": "orange",
    "prepTime": 3,
    "prepSpeed": "fast",
    "isPopular": false,
    "isNew": false
  },
  {
    "id": 14,
    "restaurantId": 2,
    "name": "Gyoza (5 pcs)",
    "description": "Pangsit panggang khas Jepang dengan isian ayam cincang dan sayuran gurih.",
    "price": 28000,
    "image": "/images/Gyoza.jpg",
    "category": "snack",
    "weight": "180g",
    "servingSize": "1 orang",
    "pieces": "5 pcs",
    "calories": 290,
    "ingredients": ["Kulit Gyoza", "Daging Ayam Cincang", "Daun Bawang", "Minyak Wijen"],
    "allergens": ["Gluten"],
    "healthCategory": "orange",
    "prepTime": 7,
    "prepSpeed": "fast",
    "isPopular": false,
    "isNew": false
  },
  {
    "id": 15,
    "restaurantId": 2,
    "name": "Matcha Latte",
    "description": "Minuman teh hijau matcha khas Kyoto berpadu dengan susu lembut.",
    "price": 22000,
    "image": "/images/Matcha.jpg",
    "category": "minuman",
    "weight": "300ml",
    "servingSize": "1 orang",
    "pieces": null,
    "calories": 150,
    "ingredients": ["Bubuk Matcha", "Susu Sapi", "Gula Cair"],
    "allergens": ["Susu"],
    "healthCategory": "blue",
    "prepTime": 3,
    "prepSpeed": "fast",
    "isPopular": false,
    "isNew": false
  },
  {
    "id": 16,
    "restaurantId": 2,
    "name": "Miso Soup",
    "description": "Sup miso hangat khas Jepang dengan tofu lembut dan rumput laut wakame.",
    "price": 15000,
    "image": "/images/Miso.jpg",
    "category": "minuman",
    "weight": "200ml",
    "servingSize": "1 orang",
    "pieces": null,
    "calories": 80,
    "ingredients": ["Pasta Miso", "Tofu Kedelai", "Wakame Rumput Laut", "Dashi"],
    "allergens": ["Kedelai"],
    "healthCategory": "orange",
    "prepTime": 5,
    "prepSpeed": "fast",
    "isPopular": false,
    "isNew": false
  },
  {
    "id": 17,
    "restaurantId": 3,
    "name": "Quinoa Buddha Bowl",
    "description": "Mangkuk sehat berisikan quinoa, alpukat, edamame, dan tahini dressing.",
    "price": 42000,
    "image": "/images/QuinoaBuddha.jpg",
    "category": "makanan-utama",
    "weight": "350g",
    "servingSize": "1 orang",
    "pieces": null,
    "calories": 380,
    "ingredients": ["Biji Quinoa", "Alpukat", "Edamame", "Ubi Manis", "Dressing Tahini"],
    "allergens": ["Kedelai"],
    "healthCategory": "blue",
    "prepTime": 7,
    "prepSpeed": "fast",
    "isPopular": true,
    "isNew": true
  },
  {
    "id": 18,
    "restaurantId": 3,
    "name": "Avocado Toast",
    "description": "Roti gandum panggang renyah dengan topping alpukat halus segar.",
    "price": 35000,
    "image": "/images/Avocadotoast.jpg",
    "category": "makanan-utama",
    "weight": "220g",
    "servingSize": "1 orang",
    "pieces": null,
    "calories": 310,
    "ingredients": ["Roti Wheat", "Alpukat Tumbuk", "Minyak Zaitun", "Biji Wijen", "Tomat Cherry"],
    "allergens": ["Gluten"],
    "healthCategory": "blue",
    "prepTime": 5,
    "prepSpeed": "fast",
    "isPopular": false,
    "isNew": true
  },
  {
    "id": 19,
    "restaurantId": 3,
    "name": "Grilled Chicken Salad",
    "description": "Salad sayuran segar dengan dada ayam panggang empuk rendah lemak.",
    "price": 38000,
    "image": "/images/Chickensalad.jpg",
    "category": "makanan-utama",
    "weight": "300g",
    "servingSize": "1 orang",
    "pieces": null,
    "calories": 290,
    "ingredients": ["Dada Ayam Panggang", "Romaine Lettuce", "Timun", "Tomat", "Dressing Lemon Zest"],
    "allergens": [],
    "healthCategory": "green",
    "prepTime": 8,
    "prepSpeed": "fast",
    "isPopular": false,
    "isNew": false
  },
  {
    "id": 20,
    "restaurantId": 3,
    "name": "Smoothie Bowl Acai",
    "description": "Smoothie acai segar bertekstur kental dengan topping chia seed & granola.",
    "price": 32000,
    "image": "/images/Smoothiebowl.jpg",
    "category": "makanan-utama",
    "weight": "280g",
    "servingSize": "1 orang",
    "pieces": null,
    "calories": 240,
    "ingredients": ["Acai Berry", "Pisang", "Granola", "Kacang Tanah", "Chia Seeds"],
    "allergens": ["Kacang Tanah"],
    "healthCategory": "blue",
    "prepTime": 5,
    "prepSpeed": "fast",
    "isPopular": false,
    "isNew": false
  },
  {
    "id": 21,
    "restaurantId": 3,
    "name": "Zucchini Noodles",
    "description": "Mie zukini segar pengganti pasta berkalori rendah dengan saus pesto basil.",
    "price": 30000,
    "image": "/images/Zucchini.jpg",
    "category": "makanan-utama",
    "weight": "250g",
    "servingSize": "1 orang",
    "pieces": null,
    "calories": 180,
    "ingredients": ["Zukini Segar", "Saus Pesto Basil", "Tomat Ceri", "Pine Nuts"],
    "allergens": [],
    "healthCategory": "green",
    "prepTime": 7,
    "prepSpeed": "fast",
    "isPopular": false,
    "isNew": false
  },
  {
    "id": 22,
    "restaurantId": 3,
    "name": "Tofu Steak",
    "description": "Steak tahu panggang gurih penyedia protein nabati sehat dengan saus teriyaki.",
    "price": 35000,
    "image": "/images/Tofusteak.jpg",
    "category": "makanan-utama",
    "weight": "280g",
    "servingSize": "1 orang",
    "pieces": null,
    "calories": 260,
    "ingredients": ["Tahu Sutra", "Saus Teriyaki", "Jamur Shiitake", "Brokoli Kukus"],
    "allergens": ["Kedelai"],
    "healthCategory": "blue",
    "prepTime": 12,
    "prepSpeed": "slow",
    "isPopular": false,
    "isNew": false
  },
  {
    "id": 23,
    "restaurantId": 3,
    "name": "Cold Pressed Juice",
    "description": "Jus ekstraksi murni dari buah dan sayuran hijau tanpa bahan pengawet.",
    "price": 25000,
    "image": "/images/Pressedjuice.jpg",
    "category": "minuman",
    "weight": "350ml",
    "servingSize": "1 orang",
    "pieces": null,
    "calories": 120,
    "ingredients": ["Kale", "Apel Hijau", "Timun", "Lemon", "Jahe"],
    "allergens": [],
    "healthCategory": "blue",
    "prepTime": 3,
    "prepSpeed": "fast",
    "isPopular": false,
    "isNew": false
  },
  {
    "id": 24,
    "restaurantId": 3,
    "name": "Oat Milk Latte",
    "description": "Kopi espresso berpadu dengan oat milk gurih bertekstur creamy.",
    "price": 28000,
    "image": "/images/Oatmilk.jpg",
    "category": "minuman",
    "weight": "300ml",
    "servingSize": "1 orang",
    "pieces": null,
    "calories": 140,
    "ingredients": ["Espresso Blend", "Susu Oat", "Gula Aren Organik"],
    "allergens": ["Gluten"],
    "healthCategory": "blue",
    "prepTime": 3,
    "prepSpeed": "fast",
    "isPopular": false,
    "isNew": false
  }
];
